// Copyright 2025 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter-convert-font-image` with arguments:
//    format         | mono16
//    unicode_glyphs | 
//    output         | qmk_firmware
//    input          | HelvetiPixel.png

// Font's metadata
// ---------------
// Glyphs:  , !, ", #, $, %, &, ', (, ), *, +, ,, -, ., /, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, :, ;, <, =, >, ?, @, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, [, \, ], ^, _, `, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, {, |, }, ~

#include <qp.h>

const uint32_t font_HelvetiPixel_length = 0;

// clang-format off
const uint8_t font_HelvetiPixel[0] = {

};
// clang-format on
